#!/usr/bin/env lua
-- let runner: transpile + run a .let file. forwards extra args.
package.path = (debug.getinfo(1).source:match"@?(.*/)" or "./").."?.lua;"..package.path
local lets = require"lets"
local file = table.remove(arg, 1) or error("usage: let <file.let> [args...]")
arg[0] = file
lets(file)
